# Generated by Django 3.0.11 on 2024-11-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('name', models.CharField(max_length=24, verbose_name='product name')),
                ('description', models.TextField(verbose_name='product description')),
                ('price', models.IntegerField(verbose_name='product price')),
                ('discount_rate', models.FloatField(verbose_name='discount_rate')),
                ('coupon_applicable', models.BooleanField(default=False, verbose_name='product coupon applicable')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='categories.Category')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='idx_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
    ]
