# Generated by Django 3.0.11 on 2024-11-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('code', models.CharField(max_length=24, verbose_name='category')),
                ('discount_rate', models.FloatField(verbose_name='discount_rate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
